### ISSUE TITLE
why not support tracing RedisSentinelConnection

### ISSUE THREAD

**Issue by wuyupengwoaini** [opentracing-contrib/java-redis-client#16]
https://github.com/opentracing-contrib/java-redis-client/blob/cf94fb09e2eba3548a36447fa90f67f1caeef64f/opentracing-redis-spring/src/main/java/io/opentracing/contrib/redis/spring/connection/TracingRedisConnectionFactory.java#L64-L67

**Comment by malafeev** [comment]
good catch @wuyupengwoaini 
will fix that
you are also welcome to submit pull requests.

**Comment by malafeev** [comment]
fixed
