### ISSUE TITLE
Redis keys length should be limited

### ISSUE THREAD

**Issue by wuyupengwoaini** [opentracing-contrib/java-redis-client#17]
https://github.com/opentracing-contrib/java-redis-client/blob/cf94fb09e2eba3548a36447fa90f67f1caeef64f/opentracing-redis-jedis/src/main/java/io/opentracing/contrib/redis/jedis/TracingJedis.java#L441-L452

When client invoked mget function,and keys length is more than hundred or more,then the span data will be so big so that it will cost so much to transport the span data and to store span data.I think it will be a little help and cost so much. so i suppose there should be a limited length.

the same to the other functions releated many keys

**Comment by malafeev** [comment]
@wuyupengwoaini how many numbers of keys you propose to limit?

**Comment by wuyupengwoaini** [comment]
I think it's better to config max length and default is 100

**Comment by malafeev** [comment]
currently I'm stuck to find a way to configure max length.
I don't want to double number of constructors. 
It looks like setter is the best choice, only desire to make parameter immutable stops me.

**Comment by wuyupengwoaini** [comment]
I think builder design pattern is a good choice. Do you think so ?

**Comment by malafeev** [comment]
fixed
