### ISSUE TITLE
Upgrade jedis to 3.3.0

### ISSUE THREAD

**Issue by dengliming** [opentracing-contrib/java-redis-client#52]
Now, jedis lastest version is 3.3.0, they fixed some bugs and add more commands support. 
See: [https://github.com/xetorthio/jedis/releases](https://github.com/xetorthio/jedis/releases)

Please see if that makes sense, and If possible, I can submit a PR. Thanks.

**Comment by malafeev** [comment]
@dengliming please submit a PR

**Comment by malafeev** [comment]
done via #53
